language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt update ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt install libwebp-dev ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install webp ; fi
  - wget http://www.imagemagick.org/download/ImageMagick.tar.gz
  - tar xf ImageMagick.tar.gz
  - mkdir /tmp/ImageMagick-lib
  - cd ImageMagick*
  - ./configure --enable-hdri --with-webp
  - make
  - sudo make install
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ldconfig ; fi

matrix:
  include:
#    - rust: stable
#      os: linux
#      env: TARGET=x86_64-unknown-linux-musl
#      install: rustup target add $TARGET
#      script: cargo test --target $TARGET
#    - rust: beta
#      os: linux
#      env: TARGET=x86_64-unknown-linux-musl
#      install: rustup target add $TARGET
#      script: cargo test --target $TARGET
#    - rust: nightly
#      os: linux
#      env: TARGET=x86_64-unknown-linux-musl
#      install: rustup target add $TARGET
#      script: cargo test --target $TARGET