[package]
name = "image-convert"
version = "0.8.7"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/image-convert"
homepage = "https://magiclen.org/image-convert"
keywords = ["image", "interlacing", "resize", "imagemagick", "conversion"]
categories = ["multimedia::images", "multimedia::encoding"]
description= "A high level library for image identification, conversion, interlacing and high quality resizing."
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "magiclen/image-convert", branch = "master" }
appveyor = { repository = "magiclen/image-convert", branch = "master", service = "github" }

[dependencies]
regex = "1"
lazy_static = "1"
starts-ends-with-caseless = "0.3.0"
magick_rust = "0.11"
enum-ordinalize = "2.2.1"
ico = "0.1.0"

[features]
none-background = []
#default = ["none-background"]