[package]
name = "image-convert"
version = "0.9.10"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"
repository = "https://github.com/magiclen/image-convert"
homepage = "https://magiclen.org/image-convert"
keywords = ["image", "interlacing", "resize", "imagemagick", "conversion"]
categories = ["multimedia::images", "multimedia::encoding"]
description= "A high level library for image identification, conversion, interlacing and high quality resizing."
readme = "README.md"
license = "MIT"
include = ["src/**/*", "Cargo.toml"]

[badges.travis-ci]
repository = "magiclen/image-convert"
branch = "master"

[dependencies]
regex = "1"
lazy_static = "1"
starts-ends-with-caseless = "0.6"
magick_rust = "0.14"
enum-ordinalize = "3.1"
ico = "0.1"

[features]
none-background = []
default = ["none-background"]